export const ClientsDatas = [
    {
        "id": 1,
        "name": "Leonore",
        "last_name": "Burchall",
        "email": "lburchall0@prweb.com",
        "phone": "434-775-5901",
        "recievables": 1627.39,
        "purvalue": 27489.95,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "1 Trailsway Hill",
        "b_street2": "PO Box 38163",
        "b_state": "Virginia",
        "b_pincode": "22111",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "6322 Ridgeview Street",
        "s_street2": "15th Floor",
        "s_state": "Texas",
        "s_pincode": "75605",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "03-01-2024",
        "updated_at": "26-01-2024"
      }, {
        "id": 2,
        "name": "Aluin",
        "last_name": "Piccard",
        "email": "apiccard1@usatoday.com",
        "phone": "812-832-9199",
        "recievables": 253.82,
        "purvalue": 9515.69,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "5 Springview Court",
        "b_street2": "Room 662",
        "b_state": "Indiana",
        "b_pincode": "47705",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "673 Fairview Junction",
        "s_street2": "PO Box 56123",
        "s_state": "Kansas",
        "s_pincode": "66642",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "03-02-2023",
        "updated_at": "02-01-2024"
      }, {
        "id": 3,
        "name": "Lucais",
        "last_name": "Abate",
        "email": "labate2@lycos.com",
        "phone": "404-821-7605",
        "recievables": 1175.0,
        "purvalue": 3791.9,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "5 Farragut Hill",
        "b_street2": "Suite 88",
        "b_state": "Georgia",
        "b_pincode": "30092",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "9862 Butterfield Trail",
        "s_street2": "Apt 769",
        "s_state": "Maryland",
        "s_pincode": "20784",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "02-01-2024",
        "updated_at": "27-04-2023"
      }, {
        "id": 4,
        "name": "Egan",
        "last_name": "Le Guin",
        "email": "eleguin3@oakley.com",
        "phone": "703-332-6908",
        "recievables": 1166.19,
        "purvalue": 2898.63,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "426 Dwight Alley",
        "b_street2": "Room 1193",
        "b_state": "Maryland",
        "b_pincode": "20904",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "538 Hintze Alley",
        "s_street2": "Apt 838",
        "s_state": "Ohio",
        "s_pincode": "43231",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "27-08-2023",
        "updated_at": "29-08-2023"
      }, {
        "id": 5,
        "name": "Ingrid",
        "last_name": "Alelsandrowicz",
        "email": "ialelsandrowicz4@wufoo.com",
        "phone": "228-227-1765",
        "recievables": 458.3,
        "purvalue": 27030.04,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "78 Cody Center",
        "b_street2": "5th Floor",
        "b_state": "Mississippi",
        "b_pincode": "39505",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "380 Rieder Road",
        "s_street2": "Suite 57",
        "s_state": "Minnesota",
        "s_pincode": "55557",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "08-09-2023",
        "updated_at": "27-02-2023"
      }, {
        "id": 6,
        "name": "Shoshana",
        "last_name": "Bairnsfather",
        "email": "sbairnsfather5@hud.gov",
        "phone": "509-250-0626",
        "recievables": 820.25,
        "purvalue": 20369.36,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "2 Oak Hill",
        "b_street2": "Apt 682",
        "b_state": "Washington",
        "b_pincode": "98907",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "61 Ilene Crossing",
        "s_street2": "PO Box 3091",
        "s_state": "Georgia",
        "s_pincode": "30096",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "22-01-2024",
        "updated_at": "01-02-2023"
      }, {
        "id": 7,
        "name": "Fiorenze",
        "last_name": "O'Cooney",
        "email": "focooney6@blogs.com",
        "phone": "309-372-5449",
        "recievables": 410.29,
        "purvalue": 16616.94,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "295 Mendota Parkway",
        "b_street2": "Apt 531",
        "b_state": "Illinois",
        "b_pincode": "61651",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "3 Carey Pass",
        "s_street2": "Apt 309",
        "s_state": "Nebraska",
        "s_pincode": "68197",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "12-11-2023",
        "updated_at": "28-02-2023"
      }, {
        "id": 8,
        "name": "Chrisy",
        "last_name": "Juschka",
        "email": "cjuschka7@yellowbook.com",
        "phone": "915-942-8078",
        "recievables": 2776.19,
        "purvalue": 13550.08,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "2 Spaight Road",
        "b_street2": "9th Floor",
        "b_state": "Texas",
        "b_pincode": "79940",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "8827 Esker Circle",
        "s_street2": "20th Floor",
        "s_state": "Texas",
        "s_pincode": "79182",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "24-11-2023",
        "updated_at": "18-04-2023"
      }, {
        "id": 9,
        "name": "Gordon",
        "last_name": "Evemy",
        "email": "gevemy8@purevolume.com",
        "phone": "806-924-5286",
        "recievables": 810.59,
        "purvalue": 21764.59,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "0 Mitchell Drive",
        "b_street2": "Apt 441",
        "b_state": "Texas",
        "b_pincode": "79415",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "6 Gerald Circle",
        "s_street2": "Apt 1170",
        "s_state": "New Jersey",
        "s_pincode": "08650",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "30-05-2023",
        "updated_at": "08-10-2023"
      }, {
        "id": 10,
        "name": "Liva",
        "last_name": "Wynrehame",
        "email": "lwynrehame9@phoca.cz",
        "phone": "510-927-5927",
        "recievables": 110.27,
        "purvalue": 5930.73,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "4 Lindbergh Parkway",
        "b_street2": "Apt 143",
        "b_state": "California",
        "b_pincode": "94616",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "8 Arapahoe Hill",
        "s_street2": "Suite 1",
        "s_state": "South Carolina",
        "s_pincode": "29305",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "05-02-2023",
        "updated_at": "01-10-2023"
      }, {
        "id": 11,
        "name": "Elset",
        "last_name": "Grichukhin",
        "email": "egrichukhina@topsy.com",
        "phone": "251-751-5344",
        "recievables": 2935.29,
        "purvalue": 21703.93,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "64 Badeau Pass",
        "b_street2": "Suite 14",
        "b_state": "Alabama",
        "b_pincode": "36670",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "7 Green Ridge Center",
        "s_street2": "7th Floor",
        "s_state": "Texas",
        "s_pincode": "78220",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "29-07-2023",
        "updated_at": "15-01-2024"
      }, {
        "id": 12,
        "name": "Augusto",
        "last_name": "Faro",
        "email": "afarob@macromedia.com",
        "phone": "706-241-0814",
        "recievables": 2702.91,
        "purvalue": 29561.91,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "42 Westerfield Trail",
        "b_street2": "Room 948",
        "b_state": "Georgia",
        "b_pincode": "30610",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "95604 Atwood Lane",
        "s_street2": "Room 1759",
        "s_state": "New York",
        "s_pincode": "10110",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "02-12-2023",
        "updated_at": "19-07-2023"
      }, {
        "id": 13,
        "name": "Kira",
        "last_name": "Perillo",
        "email": "kperilloc@salon.com",
        "phone": "828-618-9793",
        "recievables": 926.7,
        "purvalue": 13000.89,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "233 Elka Crossing",
        "b_street2": "Suite 69",
        "b_state": "North Carolina",
        "b_pincode": "28805",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "65498 Hermina Hill",
        "s_street2": "Room 1419",
        "s_state": "Kansas",
        "s_pincode": "67210",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "06-03-2023",
        "updated_at": "24-03-2023"
      }, {
        "id": 14,
        "name": "Loralie",
        "last_name": "McCandless",
        "email": "lmccandlessd@dailymotion.com",
        "phone": "256-123-5608",
        "recievables": 1629.18,
        "purvalue": 22518.16,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "82 South Alley",
        "b_street2": "Room 345",
        "b_state": "Alabama",
        "b_pincode": "35905",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "43 Hallows Avenue",
        "s_street2": "16th Floor",
        "s_state": "California",
        "s_pincode": "93794",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "02-08-2023",
        "updated_at": "10-02-2023"
      }, {
        "id": 15,
        "name": "Beale",
        "last_name": "Liptrot",
        "email": "bliptrote@privacy.gov.au",
        "phone": "304-255-4407",
        "recievables": 1045.17,
        "purvalue": 1970.79,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "6109 Hansons Point",
        "b_street2": "PO Box 57118",
        "b_state": "West Virginia",
        "b_pincode": "25705",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "7741 Namekagon Park",
        "s_street2": "PO Box 45484",
        "s_state": "Florida",
        "s_pincode": "34205",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "28-09-2023",
        "updated_at": "16-05-2023"
      }, {
        "id": 16,
        "name": "Cass",
        "last_name": "Gianolo",
        "email": "cgianolof@time.com",
        "phone": "262-632-3234",
        "recievables": 270.24,
        "purvalue": 23026.46,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "83311 John Wall Lane",
        "b_street2": "PO Box 69362",
        "b_state": "Wisconsin",
        "b_pincode": "53205",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "3 Thompson Street",
        "s_street2": "8th Floor",
        "s_state": "District of Columbia",
        "s_pincode": "20430",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "24-10-2023",
        "updated_at": "18-03-2023"
      }, {
        "id": 17,
        "name": "Molli",
        "last_name": "Markushkin",
        "email": "mmarkushking@baidu.com",
        "phone": "214-239-9008",
        "recievables": 1002.22,
        "purvalue": 7191.75,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "49074 Melrose Parkway",
        "b_street2": "PO Box 95899",
        "b_state": "Texas",
        "b_pincode": "76011",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "0 Union Street",
        "s_street2": "Room 618",
        "s_state": "Georgia",
        "s_pincode": "31416",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "17-05-2023",
        "updated_at": "12-11-2023"
      }, {
        "id": 18,
        "name": "Alverta",
        "last_name": "Dillistone",
        "email": "adillistoneh@i2i.jp",
        "phone": "971-310-0480",
        "recievables": 702.55,
        "purvalue": 29886.97,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "90 Tony Point",
        "b_street2": "PO Box 30444",
        "b_state": "Oregon",
        "b_pincode": "97312",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "90 Carberry Way",
        "s_street2": "Room 1737",
        "s_state": "Washington",
        "s_pincode": "98516",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "02-10-2023",
        "updated_at": "05-11-2023"
      }, {
        "id": 19,
        "name": "Concordia",
        "last_name": "Cordey",
        "email": "ccordeyi@reference.com",
        "phone": "615-984-7675",
        "recievables": 2395.49,
        "purvalue": 14396.86,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "837 Ronald Regan Point",
        "b_street2": "Suite 37",
        "b_state": "Tennessee",
        "b_pincode": "37228",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "452 Colorado Lane",
        "s_street2": "Suite 90",
        "s_state": "California",
        "s_pincode": "93762",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "29-03-2023",
        "updated_at": "01-05-2023"
      }, {
        "id": 20,
        "name": "Nigel",
        "last_name": "Albiston",
        "email": "nalbistonj@yellowpages.com",
        "phone": "540-597-2146",
        "recievables": 913.38,
        "purvalue": 18898.53,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "00 Anderson Avenue",
        "b_street2": "Room 1097",
        "b_state": "Virginia",
        "b_pincode": "24014",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "28 Cambridge Hill",
        "s_street2": "Suite 78",
        "s_state": "California",
        "s_pincode": "94064",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "12-03-2023",
        "updated_at": "02-12-2023"
      }, {
        "id": 21,
        "name": "Tomlin",
        "last_name": "Roddy",
        "email": "troddyk@go.com",
        "phone": "601-263-4295",
        "recievables": 850.22,
        "purvalue": 9161.78,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "80 Roxbury Plaza",
        "b_street2": "PO Box 91578",
        "b_state": "Mississippi",
        "b_pincode": "39404",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "22 East Avenue",
        "s_street2": "Apt 1074",
        "s_state": "Texas",
        "s_pincode": "79176",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "16-11-2023",
        "updated_at": "10-07-2023"
      }, {
        "id": 22,
        "name": "Karlan",
        "last_name": "Callam",
        "email": "kcallaml@twitter.com",
        "phone": "623-703-9001",
        "recievables": 2551.58,
        "purvalue": 18283.73,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "4 Melody Road",
        "b_street2": "Apt 1328",
        "b_state": "Arizona",
        "b_pincode": "85035",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "82487 Kinsman Terrace",
        "s_street2": "Suite 8",
        "s_state": "Oklahoma",
        "s_pincode": "74193",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "12-03-2023",
        "updated_at": "14-01-2024"
      }, {
        "id": 23,
        "name": "Candida",
        "last_name": "Pietrowicz",
        "email": "cpietrowiczm@paypal.com",
        "phone": "601-412-1540",
        "recievables": 1295.91,
        "purvalue": 25668.73,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "536 Graceland Pass",
        "b_street2": "PO Box 78579",
        "b_state": "Mississippi",
        "b_pincode": "39216",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "51357 Mockingbird Court",
        "s_street2": "Room 333",
        "s_state": "California",
        "s_pincode": "95852",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "19-05-2023",
        "updated_at": "24-04-2023"
      }, {
        "id": 24,
        "name": "Emanuel",
        "last_name": "Kerwen",
        "email": "ekerwenn@delicious.com",
        "phone": "305-855-7128",
        "recievables": 2258.82,
        "purvalue": 14109.21,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "27153 Hoffman Lane",
        "b_street2": "16th Floor",
        "b_state": "Florida",
        "b_pincode": "33180",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "681 Old Shore Point",
        "s_street2": "13th Floor",
        "s_state": "Florida",
        "s_pincode": "33913",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "16-09-2023",
        "updated_at": "19-02-2023"
      }, {
        "id": 25,
        "name": "Harley",
        "last_name": "Banner",
        "email": "hbannero@businesswire.com",
        "phone": "334-687-8194",
        "recievables": 1238.28,
        "purvalue": 8162.51,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "16211 Tomscot Junction",
        "b_street2": "Room 1135",
        "b_state": "Alabama",
        "b_pincode": "36104",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "319 Clove Street",
        "s_street2": "PO Box 89275",
        "s_state": "Alabama",
        "s_pincode": "36616",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "16-05-2023",
        "updated_at": "16-03-2023"
      }, {
        "id": 26,
        "name": "Gisele",
        "last_name": "Gaywood",
        "email": "ggaywoodp@jiathis.com",
        "phone": "512-165-9395",
        "recievables": 2398.04,
        "purvalue": 11749.68,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "9616 Annamark Drive",
        "b_street2": "Room 545",
        "b_state": "Texas",
        "b_pincode": "78737",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "22 Mallard Lane",
        "s_street2": "Room 548",
        "s_state": "Georgia",
        "s_pincode": "30033",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "21-02-2023",
        "updated_at": "10-05-2023"
      }, {
        "id": 27,
        "name": "Margarethe",
        "last_name": "Aldiss",
        "email": "maldissq@reddit.com",
        "phone": "949-986-5304",
        "recievables": 1759.76,
        "purvalue": 23226.9,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "39 Cordelia Lane",
        "b_street2": "Room 1899",
        "b_state": "California",
        "b_pincode": "92805",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "62120 Crownhardt Crossing",
        "s_street2": "Suite 77",
        "s_state": "South Dakota",
        "s_pincode": "57198",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "23-09-2023",
        "updated_at": "30-10-2023"
      }, {
        "id": 28,
        "name": "Dorie",
        "last_name": "Jezzard",
        "email": "djezzardr@economist.com",
        "phone": "954-605-5597",
        "recievables": 2293.1,
        "purvalue": 15922.23,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "173 Spaight Hill",
        "b_street2": "PO Box 21635",
        "b_state": "Florida",
        "b_pincode": "33315",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "46 Lawn Hill",
        "s_street2": "3rd Floor",
        "s_state": "Michigan",
        "s_pincode": "48956",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "29-06-2023",
        "updated_at": "09-07-2023"
      }, {
        "id": 29,
        "name": "Gladi",
        "last_name": "Scard",
        "email": "gscards@twitter.com",
        "phone": "406-462-4897",
        "recievables": 1107.1,
        "purvalue": 9723.33,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "82 Northridge Lane",
        "b_street2": "Room 1547",
        "b_state": "Montana",
        "b_pincode": "59771",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "84395 Blaine Pass",
        "s_street2": "Suite 44",
        "s_state": "Florida",
        "s_pincode": "32813",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "15-01-2024",
        "updated_at": "28-04-2023"
      }, {
        "id": 30,
        "name": "Erasmus",
        "last_name": "Lough",
        "email": "elought@sohu.com",
        "phone": "425-410-1081",
        "recievables": 847.04,
        "purvalue": 24172.21,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "7250 New Castle Lane",
        "b_street2": "20th Floor",
        "b_state": "Washington",
        "b_pincode": "98008",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "04 Marquette Hill",
        "s_street2": "7th Floor",
        "s_state": "Colorado",
        "s_pincode": "81505",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "09-10-2023",
        "updated_at": "20-04-2023"
      }, {
        "id": 31,
        "name": "Parnell",
        "last_name": "Glendza",
        "email": "pglendzau@howstuffworks.com",
        "phone": "212-612-6571",
        "recievables": 2158.74,
        "purvalue": 13825.78,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "99 Columbus Terrace",
        "b_street2": "PO Box 92385",
        "b_state": "New York",
        "b_pincode": "10115",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "19080 Stephen Place",
        "s_street2": "PO Box 16383",
        "s_state": "Oregon",
        "s_pincode": "97255",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "08-07-2023",
        "updated_at": "17-12-2023"
      }, {
        "id": 32,
        "name": "Glynda",
        "last_name": "Dearell",
        "email": "gdearellv@illinois.edu",
        "phone": "513-924-8840",
        "recievables": 1275.65,
        "purvalue": 17491.84,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "71671 Maywood Center",
        "b_street2": "PO Box 77710",
        "b_state": "Ohio",
        "b_pincode": "45243",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "9856 Vernon Trail",
        "s_street2": "Apt 533",
        "s_state": "Ohio",
        "s_pincode": "45807",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "08-04-2023",
        "updated_at": "06-02-2023"
      }, {
        "id": 33,
        "name": "Kylynn",
        "last_name": "Nijs",
        "email": "knijsw@businessinsider.com",
        "phone": "413-808-2273",
        "recievables": 2935.83,
        "purvalue": 26134.18,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "44564 Clove Court",
        "b_street2": "Apt 482",
        "b_state": "Massachusetts",
        "b_pincode": "01105",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "03 Red Cloud Plaza",
        "s_street2": "PO Box 36076",
        "s_state": "Ohio",
        "s_pincode": "45233",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "28-05-2023",
        "updated_at": "19-12-2023"
      }, {
        "id": 34,
        "name": "Ranna",
        "last_name": "Scupham",
        "email": "rscuphamx@sina.com.cn",
        "phone": "661-639-4349",
        "recievables": 610.08,
        "purvalue": 4567.38,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "71 Jackson Alley",
        "b_street2": "Apt 240",
        "b_state": "California",
        "b_pincode": "93591",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "77 Fairview Drive",
        "s_street2": "Suite 87",
        "s_state": "Florida",
        "s_pincode": "32854",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "07-06-2023",
        "updated_at": "02-05-2023"
      }, {
        "id": 35,
        "name": "Pepe",
        "last_name": "Lockery",
        "email": "plockeryy@wikispaces.com",
        "phone": "321-816-9734",
        "recievables": 492.11,
        "purvalue": 2257.16,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "0 Nevada Hill",
        "b_street2": "Suite 25",
        "b_state": "Florida",
        "b_pincode": "32919",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "7800 Northridge Parkway",
        "s_street2": "Apt 1129",
        "s_state": "California",
        "s_pincode": "92415",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "15-09-2023",
        "updated_at": "09-12-2023"
      }, {
        "id": 36,
        "name": "Alvis",
        "last_name": "Sims",
        "email": "asimsz@oaic.gov.au",
        "phone": "504-553-0109",
        "recievables": 2871.4,
        "purvalue": 4943.59,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "4035 Ruskin Alley",
        "b_street2": "Room 724",
        "b_state": "Louisiana",
        "b_pincode": "70149",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "58 Bartelt Parkway",
        "s_street2": "PO Box 69490",
        "s_state": "Louisiana",
        "s_pincode": "70593",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "04-02-2023",
        "updated_at": "29-03-2023"
      }, {
        "id": 37,
        "name": "Morlee",
        "last_name": "Spellissy",
        "email": "mspellissy10@earthlink.net",
        "phone": "212-103-4795",
        "recievables": 2791.49,
        "purvalue": 25796.14,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "8971 Nevada Center",
        "b_street2": "4th Floor",
        "b_state": "New York",
        "b_pincode": "11247",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "5553 Petterle Point",
        "s_street2": "Room 781",
        "s_state": "Kentucky",
        "s_pincode": "40266",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "06-08-2023",
        "updated_at": "10-09-2023"
      }, {
        "id": 38,
        "name": "Gus",
        "last_name": "Doreward",
        "email": "gdoreward11@nasa.gov",
        "phone": "918-583-0344",
        "recievables": 2940.89,
        "purvalue": 19571.99,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "62 Moose Park",
        "b_street2": "Apt 418",
        "b_state": "Oklahoma",
        "b_pincode": "74108",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "326 Parkside Point",
        "s_street2": "Room 1630",
        "s_state": "Florida",
        "s_pincode": "33283",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "10-10-2023",
        "updated_at": "11-02-2023"
      }, {
        "id": 39,
        "name": "Amalita",
        "last_name": "Kerfod",
        "email": "akerfod12@twitter.com",
        "phone": "315-173-5019",
        "recievables": 1716.92,
        "purvalue": 2528.94,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "2803 Stang Crossing",
        "b_street2": "Suite 88",
        "b_state": "New York",
        "b_pincode": "13505",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "32 Dottie Circle",
        "s_street2": "Suite 58",
        "s_state": "District of Columbia",
        "s_pincode": "20046",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "19-04-2023",
        "updated_at": "25-12-2023"
      }, {
        "id": 40,
        "name": "Sherrie",
        "last_name": "Hanne",
        "email": "shanne13@ezinearticles.com",
        "phone": "360-950-7657",
        "recievables": 2320.08,
        "purvalue": 4249.23,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "47 Burrows Junction",
        "b_street2": "Apt 838",
        "b_state": "Washington",
        "b_pincode": "98687",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "2 Paget Avenue",
        "s_street2": "Room 1588",
        "s_state": "Delaware",
        "s_pincode": "19725",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "06-02-2023",
        "updated_at": "24-01-2024"
      }, {
        "id": 41,
        "name": "Viv",
        "last_name": "Bartunek",
        "email": "vbartunek14@washington.edu",
        "phone": "786-944-6964",
        "recievables": 529.25,
        "purvalue": 27376.65,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "555 Fulton Park",
        "b_street2": "PO Box 79401",
        "b_state": "Florida",
        "b_pincode": "33180",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "6800 Pawling Junction",
        "s_street2": "Room 1351",
        "s_state": "Oregon",
        "s_pincode": "97240",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "26-03-2023",
        "updated_at": "10-10-2023"
      }, {
        "id": 42,
        "name": "Barret",
        "last_name": "Vasyagin",
        "email": "bvasyagin15@xinhuanet.com",
        "phone": "704-822-5951",
        "recievables": 773.35,
        "purvalue": 8086.46,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "27 Londonderry Junction",
        "b_street2": "PO Box 23744",
        "b_state": "North Carolina",
        "b_pincode": "28230",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "8537 Autumn Leaf Circle",
        "s_street2": "Apt 1946",
        "s_state": "Texas",
        "s_pincode": "75185",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "07-02-2023",
        "updated_at": "06-03-2023"
      }, {
        "id": 43,
        "name": "Marlow",
        "last_name": "Lightman",
        "email": "mlightman16@1und1.de",
        "phone": "330-158-3857",
        "recievables": 1136.59,
        "purvalue": 9550.31,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "58091 Prairieview Junction",
        "b_street2": "14th Floor",
        "b_state": "Ohio",
        "b_pincode": "44315",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "98421 Union Avenue",
        "s_street2": "PO Box 77907",
        "s_state": "New York",
        "s_pincode": "10009",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "23-03-2023",
        "updated_at": "31-01-2023"
      }, {
        "id": 44,
        "name": "Betsy",
        "last_name": "Sizey",
        "email": "bsizey17@marriott.com",
        "phone": "850-483-8780",
        "recievables": 1156.22,
        "purvalue": 2691.37,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "77 Sugar Road",
        "b_street2": "Room 931",
        "b_state": "Florida",
        "b_pincode": "32520",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "460 Waywood Plaza",
        "s_street2": "15th Floor",
        "s_state": "New York",
        "s_pincode": "12222",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "22-07-2023",
        "updated_at": "14-03-2023"
      }, {
        "id": 45,
        "name": "Ken",
        "last_name": "Wisker",
        "email": "kwisker18@rambler.ru",
        "phone": "517-874-1908",
        "recievables": 1560.63,
        "purvalue": 1112.3,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "229 Artisan Avenue",
        "b_street2": "PO Box 47705",
        "b_state": "Michigan",
        "b_pincode": "48930",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "3088 Corry Point",
        "s_street2": "PO Box 9437",
        "s_state": "District of Columbia",
        "s_pincode": "20205",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "27-02-2023",
        "updated_at": "17-05-2023"
      }, {
        "id": 46,
        "name": "Kiele",
        "last_name": "Levick",
        "email": "klevick19@sun.com",
        "phone": "901-148-3610",
        "recievables": 2469.65,
        "purvalue": 1344.63,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "421 Merrick Terrace",
        "b_street2": "Suite 38",
        "b_state": "Tennessee",
        "b_pincode": "38161",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "25 Moland Hill",
        "s_street2": "PO Box 28411",
        "s_state": "New Mexico",
        "s_pincode": "87195",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "05-04-2023",
        "updated_at": "13-01-2024"
      }, {
        "id": 47,
        "name": "Daisi",
        "last_name": "Shiell",
        "email": "dshiell1a@economist.com",
        "phone": "504-251-7899",
        "recievables": 1725.01,
        "purvalue": 9034.64,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "68345 Graceland Center",
        "b_street2": "Room 840",
        "b_state": "Louisiana",
        "b_pincode": "70033",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "20 Mcbride Drive",
        "s_street2": "PO Box 85129",
        "s_state": "Ohio",
        "s_pincode": "43226",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "27-12-2023",
        "updated_at": "30-04-2023"
      }, {
        "id": 48,
        "name": "Gardy",
        "last_name": "Billingsley",
        "email": "gbillingsley1b@etsy.com",
        "phone": "773-701-3039",
        "recievables": 496.0,
        "purvalue": 25118.64,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "3672 Fieldstone Trail",
        "b_street2": "Apt 1028",
        "b_state": "Illinois",
        "b_pincode": "60657",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "766 Kenwood Parkway",
        "s_street2": "PO Box 91237",
        "s_state": "Massachusetts",
        "s_pincode": "01610",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "25-12-2023",
        "updated_at": "10-06-2023"
      }, {
        "id": 49,
        "name": "Rochette",
        "last_name": "Keuntje",
        "email": "rkeuntje1c@state.tx.us",
        "phone": "901-397-6698",
        "recievables": 1656.51,
        "purvalue": 8949.65,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "69 Jenifer Lane",
        "b_street2": "Suite 41",
        "b_state": "Tennessee",
        "b_pincode": "38136",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "8099 Harbort Road",
        "s_street2": "Apt 178",
        "s_state": "Georgia",
        "s_pincode": "30343",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "12-05-2023",
        "updated_at": "02-08-2023"
      }, {
        "id": 50,
        "name": "Loni",
        "last_name": "Standbrooke",
        "email": "lstandbrooke1d@sourceforge.net",
        "phone": "571-955-4638",
        "recievables": 2141.09,
        "purvalue": 12177.63,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "842 Continental Trail",
        "b_street2": "Room 1923",
        "b_state": "Virginia",
        "b_pincode": "22119",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "8843 Rigney Pass",
        "s_street2": "Room 860",
        "s_state": "Ohio",
        "s_pincode": "44177",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "30-01-2023",
        "updated_at": "09-03-2023"
      }, {
        "id": 51,
        "name": "Winfield",
        "last_name": "Semechik",
        "email": "wsemechik1e@usatoday.com",
        "phone": "559-471-5490",
        "recievables": 2541.75,
        "purvalue": 19888.82,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "05 Mayfield Parkway",
        "b_street2": "Room 1590",
        "b_state": "California",
        "b_pincode": "93750",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "8895 Lotheville Alley",
        "s_street2": "PO Box 26190",
        "s_state": "Illinois",
        "s_pincode": "61629",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "17-03-2023",
        "updated_at": "14-05-2023"
      }, {
        "id": 52,
        "name": "Lorene",
        "last_name": "MacGiolla Pheadair",
        "email": "lmacgiollapheadair1f@rediff.com",
        "phone": "754-964-5405",
        "recievables": 382.32,
        "purvalue": 29408.95,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "75785 Donald Park",
        "b_street2": "Suite 14",
        "b_state": "Florida",
        "b_pincode": "33075",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "1 Saint Paul Road",
        "s_street2": "Apt 1965",
        "s_state": "Florida",
        "s_pincode": "33075",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "06-09-2023",
        "updated_at": "14-11-2023"
      }, {
        "id": 53,
        "name": "Wallace",
        "last_name": "Mabee",
        "email": "wmabee1g@360.cn",
        "phone": "714-305-8499",
        "recievables": 1512.29,
        "purvalue": 26767.44,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "24129 Elka Road",
        "b_street2": "PO Box 41297",
        "b_state": "California",
        "b_pincode": "92862",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "03083 Del Sol Court",
        "s_street2": "Apt 1980",
        "s_state": "Florida",
        "s_pincode": "34615",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "28-02-2023",
        "updated_at": "17-12-2023"
      }, {
        "id": 54,
        "name": "Diena",
        "last_name": "Newlove",
        "email": "dnewlove1h@hexun.com",
        "phone": "916-339-0078",
        "recievables": 1687.3,
        "purvalue": 6366.09,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "981 School Trail",
        "b_street2": "Apt 1399",
        "b_state": "California",
        "b_pincode": "94250",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "53706 Morningstar Plaza",
        "s_street2": "Room 1859",
        "s_state": "Tennessee",
        "s_pincode": "37228",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "07-11-2023",
        "updated_at": "03-02-2023"
      }, {
        "id": 55,
        "name": "Maurits",
        "last_name": "Gouldsmith",
        "email": "mgouldsmith1i@artisteer.com",
        "phone": "608-521-5435",
        "recievables": 1694.75,
        "purvalue": 25574.8,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "2230 Division Center",
        "b_street2": "Room 1335",
        "b_state": "Wisconsin",
        "b_pincode": "53705",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "459 Holy Cross Road",
        "s_street2": "Suite 25",
        "s_state": "Arizona",
        "s_pincode": "85284",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "07-10-2023",
        "updated_at": "19-09-2023"
      }, {
        "id": 56,
        "name": "Brina",
        "last_name": "Baudts",
        "email": "bbaudts1j@weibo.com",
        "phone": "203-116-2140",
        "recievables": 1661.53,
        "purvalue": 20184.42,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "3424 Melby Trail",
        "b_street2": "Room 270",
        "b_state": "Connecticut",
        "b_pincode": "06854",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "930 Melvin Avenue",
        "s_street2": "17th Floor",
        "s_state": "Tennessee",
        "s_pincode": "38161",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "24-08-2023",
        "updated_at": "29-04-2023"
      }, {
        "id": 57,
        "name": "Goldia",
        "last_name": "Harmstone",
        "email": "gharmstone1k@apple.com",
        "phone": "602-998-4278",
        "recievables": 1994.24,
        "purvalue": 24155.81,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "1 Shoshone Circle",
        "b_street2": "PO Box 40044",
        "b_state": "Arizona",
        "b_pincode": "85010",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "2646 Fallview Park",
        "s_street2": "3rd Floor",
        "s_state": "Ohio",
        "s_pincode": "44191",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "21-11-2023",
        "updated_at": "20-05-2023"
      }, {
        "id": 58,
        "name": "Jarid",
        "last_name": "Blencoe",
        "email": "jblencoe1l@wordpress.com",
        "phone": "303-603-6088",
        "recievables": 442.7,
        "purvalue": 8014.19,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "436 Ludington Lane",
        "b_street2": "Apt 1611",
        "b_state": "Colorado",
        "b_pincode": "80217",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "29 Nova Avenue",
        "s_street2": "Suite 18",
        "s_state": "Virginia",
        "s_pincode": "23509",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "30-05-2023",
        "updated_at": "08-07-2023"
      }, {
        "id": 59,
        "name": "Alexa",
        "last_name": "Ayto",
        "email": "aayto1m@google.it",
        "phone": "214-675-1337",
        "recievables": 1999.6,
        "purvalue": 21926.11,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "031 Armistice Lane",
        "b_street2": "Suite 19",
        "b_state": "Texas",
        "b_pincode": "75372",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "7 Duke Junction",
        "s_street2": "Room 1750",
        "s_state": "Iowa",
        "s_pincode": "50981",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "11-12-2023",
        "updated_at": "26-12-2023"
      }, {
        "id": 60,
        "name": "Edyth",
        "last_name": "Jandl",
        "email": "ejandl1n@moonfruit.com",
        "phone": "414-565-3223",
        "recievables": 2804.7,
        "purvalue": 25904.36,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "6802 Stephen Point",
        "b_street2": "14th Floor",
        "b_state": "Wisconsin",
        "b_pincode": "53220",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "4526 Algoma Trail",
        "s_street2": "Apt 546",
        "s_state": "Ohio",
        "s_pincode": "45254",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "26-12-2023",
        "updated_at": "29-07-2023"
      }, {
        "id": 61,
        "name": "Jayne",
        "last_name": "Kyles",
        "email": "jkyles1o@nyu.edu",
        "phone": "205-891-7989",
        "recievables": 641.7,
        "purvalue": 12793.43,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "4 Burrows Way",
        "b_street2": "Apt 1485",
        "b_state": "Alabama",
        "b_pincode": "35285",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "6483 Dexter Drive",
        "s_street2": "Room 1928",
        "s_state": "Michigan",
        "s_pincode": "48232",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "09-02-2023",
        "updated_at": "24-07-2023"
      }, {
        "id": 62,
        "name": "Kennith",
        "last_name": "Van der Kruys",
        "email": "kvanderkruys1p@unblog.fr",
        "phone": "336-934-3647",
        "recievables": 2617.91,
        "purvalue": 21333.48,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "6 Stone Corner Point",
        "b_street2": "Suite 35",
        "b_state": "North Carolina",
        "b_pincode": "27499",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "4871 Schurz Park",
        "s_street2": "Suite 39",
        "s_state": "South Carolina",
        "s_pincode": "29208",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "11-10-2023",
        "updated_at": "07-10-2023"
      }, {
        "id": 63,
        "name": "Abbey",
        "last_name": "Pettisall",
        "email": "apettisall1q@java.com",
        "phone": "404-740-4852",
        "recievables": 2968.54,
        "purvalue": 28020.67,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "9125 Clyde Gallagher Pass",
        "b_street2": "Suite 76",
        "b_state": "Georgia",
        "b_pincode": "30351",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "96805 Transport Way",
        "s_street2": "Apt 549",
        "s_state": "North Carolina",
        "s_pincode": "27455",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "10-08-2023",
        "updated_at": "09-04-2023"
      }, {
        "id": 64,
        "name": "Loretta",
        "last_name": "Drage",
        "email": "ldrage1r@prlog.org",
        "phone": "212-838-0184",
        "recievables": 662.14,
        "purvalue": 21293.05,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "0 Division Alley",
        "b_street2": "18th Floor",
        "b_state": "New York",
        "b_pincode": "10125",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "07928 Gateway Court",
        "s_street2": "19th Floor",
        "s_state": "Oklahoma",
        "s_pincode": "73135",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "11-05-2023",
        "updated_at": "26-12-2023"
      }, {
        "id": 65,
        "name": "Torrey",
        "last_name": "Redit",
        "email": "tredit1s@ucla.edu",
        "phone": "203-963-1876",
        "recievables": 1021.35,
        "purvalue": 11718.44,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "825 Susan Terrace",
        "b_street2": "Suite 74",
        "b_state": "Connecticut",
        "b_pincode": "06673",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "65 Jenifer Plaza",
        "s_street2": "Apt 801",
        "s_state": "Utah",
        "s_pincode": "84145",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "07-12-2023",
        "updated_at": "01-05-2023"
      }, {
        "id": 66,
        "name": "Babara",
        "last_name": "Matas",
        "email": "bmatas1t@deliciousdays.com",
        "phone": "413-936-4700",
        "recievables": 2975.41,
        "purvalue": 3458.25,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "31553 Kim Terrace",
        "b_street2": "Room 1119",
        "b_state": "Massachusetts",
        "b_pincode": "01129",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "42 Havey Hill",
        "s_street2": "PO Box 96848",
        "s_state": "Michigan",
        "s_pincode": "49544",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "29-07-2023",
        "updated_at": "29-06-2023"
      }, {
        "id": 67,
        "name": "Carolynn",
        "last_name": "Crookes",
        "email": "ccrookes1u@walmart.com",
        "phone": "312-793-9224",
        "recievables": 2730.33,
        "purvalue": 19844.86,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "44 Oak Point",
        "b_street2": "Suite 87",
        "b_state": "Illinois",
        "b_pincode": "60697",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "5374 Nancy Lane",
        "s_street2": "PO Box 93732",
        "s_state": "Indiana",
        "s_pincode": "47719",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "04-09-2023",
        "updated_at": "15-02-2023"
      }, {
        "id": 68,
        "name": "Gannon",
        "last_name": "Rumble",
        "email": "grumble1v@bluehost.com",
        "phone": "212-346-9488",
        "recievables": 1016.29,
        "purvalue": 1385.02,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "0 Mesta Point",
        "b_street2": "1st Floor",
        "b_state": "New York",
        "b_pincode": "10105",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "21 Esker Point",
        "s_street2": "PO Box 31903",
        "s_state": "California",
        "s_pincode": "91205",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "21-07-2023",
        "updated_at": "01-02-2023"
      }, {
        "id": 69,
        "name": "Yevette",
        "last_name": "Egarr",
        "email": "yegarr1w@istockphoto.com",
        "phone": "214-685-0764",
        "recievables": 177.56,
        "purvalue": 17378.76,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "21979 Boyd Pass",
        "b_street2": "1st Floor",
        "b_state": "Texas",
        "b_pincode": "75226",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "00 Eagan Lane",
        "s_street2": "PO Box 57658",
        "s_state": "Texas",
        "s_pincode": "79769",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "02-10-2023",
        "updated_at": "14-09-2023"
      }, {
        "id": 70,
        "name": "Marchelle",
        "last_name": "Spratling",
        "email": "mspratling1x@lulu.com",
        "phone": "704-844-4882",
        "recievables": 1894.62,
        "purvalue": 17466.23,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "94434 Dottie Alley",
        "b_street2": "Apt 196",
        "b_state": "North Carolina",
        "b_pincode": "28242",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "73 Debra Plaza",
        "s_street2": "PO Box 79652",
        "s_state": "Colorado",
        "s_pincode": "80126",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "13-05-2023",
        "updated_at": "04-07-2023"
      }, {
        "id": 71,
        "name": "Candace",
        "last_name": "Beton",
        "email": "cbeton1y@goodreads.com",
        "phone": "903-227-2551",
        "recievables": 2395.11,
        "purvalue": 2965.44,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "76042 Gina Pass",
        "b_street2": "8th Floor",
        "b_state": "Texas",
        "b_pincode": "75507",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "93 Lien Avenue",
        "s_street2": "9th Floor",
        "s_state": "Ohio",
        "s_pincode": "45470",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "18-11-2023",
        "updated_at": "11-11-2023"
      }, {
        "id": 72,
        "name": "Chev",
        "last_name": "Lillico",
        "email": "clillico1z@topsy.com",
        "phone": "616-122-2482",
        "recievables": 485.29,
        "purvalue": 1188.49,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "93120 Gateway Plaza",
        "b_street2": "Suite 94",
        "b_state": "Michigan",
        "b_pincode": "49510",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "30074 Golf View Plaza",
        "s_street2": "Suite 25",
        "s_state": "California",
        "s_pincode": "91328",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "23-11-2023",
        "updated_at": "24-02-2023"
      }, {
        "id": 73,
        "name": "Noellyn",
        "last_name": "Mainstone",
        "email": "nmainstone20@flavors.me",
        "phone": "954-496-8070",
        "recievables": 1475.13,
        "purvalue": 14955.06,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "91135 Rowland Crossing",
        "b_street2": "6th Floor",
        "b_state": "Florida",
        "b_pincode": "33315",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "97089 Waywood Alley",
        "s_street2": "Suite 94",
        "s_state": "Florida",
        "s_pincode": "32412",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "26-11-2023",
        "updated_at": "15-11-2023"
      }, {
        "id": 74,
        "name": "Wally",
        "last_name": "Cranmer",
        "email": "wcranmer21@buzzfeed.com",
        "phone": "863-347-6407",
        "recievables": 1980.37,
        "purvalue": 15243.48,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "9 Rusk Hill",
        "b_street2": "Suite 22",
        "b_state": "Florida",
        "b_pincode": "33811",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "66626 Maywood Lane",
        "s_street2": "PO Box 82737",
        "s_state": "Texas",
        "s_pincode": "76544",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "18-12-2023",
        "updated_at": "20-05-2023"
      }, {
        "id": 75,
        "name": "Symon",
        "last_name": "Nevinson",
        "email": "snevinson22@china.com.cn",
        "phone": "510-460-2875",
        "recievables": 1186.26,
        "purvalue": 26192.46,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "590 Lighthouse Bay Junction",
        "b_street2": "PO Box 63718",
        "b_state": "California",
        "b_pincode": "94807",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "12 Donald Road",
        "s_street2": "Suite 45",
        "s_state": "California",
        "s_pincode": "90101",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "27-10-2023",
        "updated_at": "01-10-2023"
      }, {
        "id": 76,
        "name": "Tabatha",
        "last_name": "Smallridge",
        "email": "tsmallridge23@pinterest.com",
        "phone": "503-488-4218",
        "recievables": 2076.3,
        "purvalue": 13312.12,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "1433 Gateway Park",
        "b_street2": "3rd Floor",
        "b_state": "Oregon",
        "b_pincode": "97229",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "467 Nevada Plaza",
        "s_street2": "5th Floor",
        "s_state": "Connecticut",
        "s_pincode": "06673",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "08-10-2023",
        "updated_at": "05-06-2023"
      }, {
        "id": 77,
        "name": "Caprice",
        "last_name": "Schops",
        "email": "cschops24@whitehouse.gov",
        "phone": "718-813-7881",
        "recievables": 2781.21,
        "purvalue": 22093.39,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "13 8th Street",
        "b_street2": "15th Floor",
        "b_state": "New York",
        "b_pincode": "11225",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "74951 Arrowood Junction",
        "s_street2": "Suite 84",
        "s_state": "Florida",
        "s_pincode": "32835",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "10-12-2023",
        "updated_at": "07-05-2023"
      }, {
        "id": 78,
        "name": "Ailina",
        "last_name": "Thowless",
        "email": "athowless25@wp.com",
        "phone": "757-860-2921",
        "recievables": 1399.0,
        "purvalue": 8545.99,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "24382 Atwood Point",
        "b_street2": "Suite 23",
        "b_state": "Virginia",
        "b_pincode": "23520",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "11639 Algoma Plaza",
        "s_street2": "9th Floor",
        "s_state": "Alabama",
        "s_pincode": "36134",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "22-11-2023",
        "updated_at": "23-12-2023"
      }, {
        "id": 79,
        "name": "Mia",
        "last_name": "Raulin",
        "email": "mraulin26@sina.com.cn",
        "phone": "801-424-5536",
        "recievables": 2909.07,
        "purvalue": 22224.8,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "1 Debs Place",
        "b_street2": "Room 128",
        "b_state": "Utah",
        "b_pincode": "84152",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "1815 Golf View Junction",
        "s_street2": "Suite 24",
        "s_state": "Texas",
        "s_pincode": "79176",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "07-08-2023",
        "updated_at": "08-04-2023"
      }, {
        "id": 80,
        "name": "Debera",
        "last_name": "Rumbold",
        "email": "drumbold27@ucsd.edu",
        "phone": "512-247-7754",
        "recievables": 2234.67,
        "purvalue": 29583.59,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "859 Luster Center",
        "b_street2": "Suite 14",
        "b_state": "Texas",
        "b_pincode": "78749",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "77594 Hoffman Road",
        "s_street2": "Room 332",
        "s_state": "Texas",
        "s_pincode": "79188",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "21-01-2024",
        "updated_at": "25-08-2023"
      }, {
        "id": 81,
        "name": "Dulcy",
        "last_name": "Igoe",
        "email": "digoe28@guardian.co.uk",
        "phone": "520-794-9434",
        "recievables": 2963.87,
        "purvalue": 2777.95,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "44397 Bluestem Way",
        "b_street2": "4th Floor",
        "b_state": "Arizona",
        "b_pincode": "85710",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "13664 Lukken Crossing",
        "s_street2": "Suite 17",
        "s_state": "California",
        "s_pincode": "92137",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "28-11-2023",
        "updated_at": "30-09-2023"
      }, {
        "id": 82,
        "name": "Ian",
        "last_name": "Budd",
        "email": "ibudd29@domainmarket.com",
        "phone": "773-473-8392",
        "recievables": 1959.32,
        "purvalue": 22641.26,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "2 Monterey Park",
        "b_street2": "Room 238",
        "b_state": "Illinois",
        "b_pincode": "60636",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "76 Scoville Crossing",
        "s_street2": "Apt 1515",
        "s_state": "California",
        "s_pincode": "94230",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "27-01-2024",
        "updated_at": "26-03-2023"
      }, {
        "id": 83,
        "name": "Chryste",
        "last_name": "Safell",
        "email": "csafell2a@unicef.org",
        "phone": "917-747-1383",
        "recievables": 682.73,
        "purvalue": 8453.05,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "3 Village Green Alley",
        "b_street2": "Suite 39",
        "b_state": "New York",
        "b_pincode": "10464",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "0 4th Court",
        "s_street2": "Suite 67",
        "s_state": "Virginia",
        "s_pincode": "24024",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "30-08-2023",
        "updated_at": "25-08-2023"
      }, {
        "id": 84,
        "name": "Oralle",
        "last_name": "Edlestone",
        "email": "oedlestone2b@nifty.com",
        "phone": "917-513-3774",
        "recievables": 1072.58,
        "purvalue": 8294.22,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "7 Beilfuss Court",
        "b_street2": "15th Floor",
        "b_state": "New York",
        "b_pincode": "10110",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "260 Butternut Court",
        "s_street2": "PO Box 42072",
        "s_state": "Minnesota",
        "s_pincode": "55585",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "11-10-2023",
        "updated_at": "12-11-2023"
      }, {
        "id": 85,
        "name": "Sloan",
        "last_name": "Hounsham",
        "email": "shounsham2c@upenn.edu",
        "phone": "412-260-8791",
        "recievables": 724.75,
        "purvalue": 19007.81,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "709 High Crossing Avenue",
        "b_street2": "5th Floor",
        "b_state": "Pennsylvania",
        "b_pincode": "15286",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "0416 Russell Lane",
        "s_street2": "1st Floor",
        "s_state": "Pennsylvania",
        "s_pincode": "15266",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "23-03-2023",
        "updated_at": "20-02-2023"
      }, {
        "id": 86,
        "name": "Ximenes",
        "last_name": "Seaking",
        "email": "xseaking2d@google.fr",
        "phone": "314-292-2152",
        "recievables": 2254.52,
        "purvalue": 21992.81,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "4 Arapahoe Pass",
        "b_street2": "9th Floor",
        "b_state": "Missouri",
        "b_pincode": "63169",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "331 Graedel Alley",
        "s_street2": "PO Box 30360",
        "s_state": "Georgia",
        "s_pincode": "31605",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "29-10-2023",
        "updated_at": "21-02-2023"
      }, {
        "id": 87,
        "name": "Gloriane",
        "last_name": "Verrechia",
        "email": "gverrechia2e@squidoo.com",
        "phone": "646-957-7069",
        "recievables": 2613.45,
        "purvalue": 25922.38,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "3633 Esch Parkway",
        "b_street2": "Room 820",
        "b_state": "New York",
        "b_pincode": "10155",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "08706 Texas Way",
        "s_street2": "PO Box 33618",
        "s_state": "Florida",
        "s_pincode": "33153",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "01-06-2023",
        "updated_at": "10-06-2023"
      }, {
        "id": 88,
        "name": "Claybourne",
        "last_name": "Parriss",
        "email": "cparriss2f@state.tx.us",
        "phone": "212-727-8128",
        "recievables": 2734.8,
        "purvalue": 19019.42,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "24359 Riverside Way",
        "b_street2": "Suite 36",
        "b_state": "New York",
        "b_pincode": "10150",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "5862 Duke Point",
        "s_street2": "Room 152",
        "s_state": "Georgia",
        "s_pincode": "31605",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "06-08-2023",
        "updated_at": "18-11-2023"
      }, {
        "id": 89,
        "name": "Eustace",
        "last_name": "Balsom",
        "email": "ebalsom2g@webnode.com",
        "phone": "915-976-4878",
        "recievables": 2318.97,
        "purvalue": 23688.86,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "2862 Veith Junction",
        "b_street2": "Suite 100",
        "b_state": "Texas",
        "b_pincode": "79994",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "935 Mandrake Court",
        "s_street2": "PO Box 15734",
        "s_state": "Minnesota",
        "s_pincode": "55905",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "18-04-2023",
        "updated_at": "07-09-2023"
      }, {
        "id": 90,
        "name": "Heriberto",
        "last_name": "Oades",
        "email": "hoades2h@jalbum.net",
        "phone": "386-821-4540",
        "recievables": 775.22,
        "purvalue": 17874.95,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "72 Forest Center",
        "b_street2": "Apt 158",
        "b_state": "Florida",
        "b_pincode": "32118",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "267 Messerschmidt Place",
        "s_street2": "Room 13",
        "s_state": "Florida",
        "s_pincode": "32964",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "29-01-2023",
        "updated_at": "18-12-2023"
      }, {
        "id": 91,
        "name": "Melody",
        "last_name": "Egerton",
        "email": "megerton2i@google.ca",
        "phone": "814-730-3003",
        "recievables": 331.3,
        "purvalue": 14126.44,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "98187 Blaine Court",
        "b_street2": "Room 661",
        "b_state": "Pennsylvania",
        "b_pincode": "15906",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "99885 Pankratz Place",
        "s_street2": "Apt 1288",
        "s_state": "New Jersey",
        "s_pincode": "08603",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "19-05-2023",
        "updated_at": "27-02-2023"
      }, {
        "id": 92,
        "name": "Dulcine",
        "last_name": "Berthel",
        "email": "dberthel2j@upenn.edu",
        "phone": "229-351-7804",
        "recievables": 616.46,
        "purvalue": 5102.35,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "504 Drewry Lane",
        "b_street2": "Suite 93",
        "b_state": "Georgia",
        "b_pincode": "31605",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "2278 Forster Parkway",
        "s_street2": "Apt 161",
        "s_state": "Florida",
        "s_pincode": "32277",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "03-04-2023",
        "updated_at": "23-03-2023"
      }, {
        "id": 93,
        "name": "Edgar",
        "last_name": "Nind",
        "email": "enind2k@latimes.com",
        "phone": "480-964-2182",
        "recievables": 2306.49,
        "purvalue": 23962.77,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "93 Colorado Alley",
        "b_street2": "Suite 97",
        "b_state": "Arizona",
        "b_pincode": "85025",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "61 Truax Avenue",
        "s_street2": "PO Box 5355",
        "s_state": "Arizona",
        "s_pincode": "85005",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "23-04-2023",
        "updated_at": "14-09-2023"
      }, {
        "id": 94,
        "name": "Cyrille",
        "last_name": "McGuggy",
        "email": "cmcguggy2l@nyu.edu",
        "phone": "810-562-7170",
        "recievables": 2874.09,
        "purvalue": 14438.96,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "7 Leroy Drive",
        "b_street2": "Room 1937",
        "b_state": "Michigan",
        "b_pincode": "48555",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "3568 Independence Trail",
        "s_street2": "PO Box 59212",
        "s_state": "Florida",
        "s_pincode": "34611",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "15-05-2023",
        "updated_at": "29-05-2023"
      }, {
        "id": 95,
        "name": "Zabrina",
        "last_name": "Pendrey",
        "email": "zpendrey2m@nature.com",
        "phone": "909-234-5141",
        "recievables": 421.45,
        "purvalue": 1210.8,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "8 Mitchell Junction",
        "b_street2": "PO Box 68494",
        "b_state": "California",
        "b_pincode": "92424",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "077 Badeau Center",
        "s_street2": "Room 590",
        "s_state": "Hawaii",
        "s_pincode": "96820",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "29-08-2023",
        "updated_at": "17-01-2024"
      }, {
        "id": 96,
        "name": "Jessika",
        "last_name": "Reynish",
        "email": "jreynish2n@miibeian.gov.cn",
        "phone": "505-852-5631",
        "recievables": 1942.39,
        "purvalue": 21006.68,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "55996 Emmet Junction",
        "b_street2": "Room 1394",
        "b_state": "New Mexico",
        "b_pincode": "88006",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "76947 Vermont Terrace",
        "s_street2": "Room 311",
        "s_state": "Arizona",
        "s_pincode": "85305",
        "status": 0,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "02-12-2023",
        "updated_at": "29-04-2023"
      }, {
        "id": 97,
        "name": "Piotr",
        "last_name": "Gueny",
        "email": "pgueny2o@hp.com",
        "phone": "571-317-6647",
        "recievables": 530.33,
        "purvalue": 7700.8,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "5707 Kropf Alley",
        "b_street2": "Room 1557",
        "b_state": "Virginia",
        "b_pincode": "22156",
        "s_attention": "Work",
        "s_country": "United States",
        "s_street": "26617 Ruskin Pass",
        "s_street2": "10th Floor",
        "s_state": "California",
        "s_pincode": "92805",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "13-12-2023",
        "updated_at": "14-04-2023"
      }, {
        "id": 98,
        "name": "Alane",
        "last_name": "Buffey",
        "email": "abuffey2p@apache.org",
        "phone": "763-762-5776",
        "recievables": 1663.52,
        "purvalue": 15513.8,
        "b_attention": "Work",
        "b_country": "United States",
        "b_street": "06871 Oak Valley Park",
        "b_street2": "PO Box 83321",
        "b_state": "Minnesota",
        "b_pincode": "55585",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "462 Gerald Way",
        "s_street2": "PO Box 20631",
        "s_state": "California",
        "s_pincode": "92867",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "30-07-2023",
        "updated_at": "09-08-2023"
      }, {
        "id": 99,
        "name": "Brianna",
        "last_name": "Dallosso",
        "email": "bdallosso2q@twitpic.com",
        "phone": "920-112-0427",
        "recievables": 1791.48,
        "purvalue": 17698.43,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "6751 Rockefeller Plaza",
        "b_street2": "Apt 633",
        "b_state": "Wisconsin",
        "b_pincode": "54305",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "4 Bashford Center",
        "s_street2": "Apt 1822",
        "s_state": "Ohio",
        "s_pincode": "44111",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "22-11-2023",
        "updated_at": "28-04-2023"
      }, {
        "id": 100,
        "name": "Antonia",
        "last_name": "Saberton",
        "email": "asaberton2r@tumblr.com",
        "phone": "559-656-3938",
        "recievables": 1251.24,
        "purvalue": 18571.18,
        "b_attention": "Home",
        "b_country": "United States",
        "b_street": "67030 Melby Center",
        "b_street2": "PO Box 96447",
        "b_state": "California",
        "b_pincode": "93773",
        "s_attention": "Home",
        "s_country": "United States",
        "s_street": "055 Harper Crossing",
        "s_street2": "Apt 1608",
        "s_state": "Texas",
        "s_pincode": "75265",
        "status": 1,
        "created_by": 1,
        "updated_by": 1,
        "created_at": "27-06-2023",
        "updated_at": "20-11-2023"
      }
];